/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aspuser;
import java.util.List;
import java.util.Arrays;
import java.util.ArrayList;
import java.lang.Runtime;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Enumeration;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author selin
 */
public class NewJFrame extends javax.swing.JFrame {

     public String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }

        return null;
    }
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        fileChooser = new javax.swing.JFileChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        fileChooser.setDialogTitle("This is an open dialog");
        fileChooser.setFileFilter(new MyCustomFilter());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ASP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 204, 204))); // NOI18N

        jLabel2.setText("      Please choose the SMP variation");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SMP with Ties and Inc.", "Sex Equal", "Egalitarian", "Min Regret", "Max Cardinality", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Please specify the input format");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Rank");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Preference");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setRows(5);
        textArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(textArea);

        jButton1.setText("Run");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jRadioButton1)
                                        .addGap(38, 38, 38)
                                        .addComponent(jRadioButton2)))))
                        .addGap(0, 147, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Open");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   File file;

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    String command="null";

    if (getSelectedButtonText(buttonGroup1) == "Rank"){

       List<String> lines = new ArrayList<String>();
        String s="";
        BufferedReader br = null;
        s =  textArea.getText();
        lines = Arrays.asList(s.split("\n"));
        
       if(lines.size() < 2){
           JOptionPane.showMessageDialog(this, "Invalid Input!");
           return;
   }

       int m_size = Integer.parseInt(lines.get(0));
       int w_size = Integer.parseInt(lines.get(1));
          int m_maxLen = 0;
   int w_maxLen = 0;

   for(int i=2;i<m_size+2;i++ )
   {
       if(lines.get(i).length() > m_maxLen)
         m_maxLen = lines.get(i).length();
   }
    for(int i=m_size+2;i<w_size+m_size+2;i++ )
   {
       if(lines.get(i).length() > w_maxLen)
         w_maxLen = lines.get(i).length();
   }


           if(lines.size() != m_size + w_size + 2 || m_maxLen > 2*m_size || w_maxLen > 2*w_size ){
           JOptionPane.showMessageDialog(this, "Invalid Input!");
           return;
   }
       String[] m_preflists;
       ArrayList<String[]> split_w = new ArrayList<String[]>();
       ArrayList<String[]> split_m = new ArrayList<String[]>();

      for(int i=0; i<m_size;i++)
      {
         String k=lines.get(i + 2);
         String[] l=k.split(" ");
          split_m.add(l);
      }

      for(int i=0; i<w_size;i++)
      {
         String k=lines.get(i + 2 + m_size);
         String[] l=k.split(" ");
          split_w.add(l);
      }


      BufferedWriter bw = null;
      FileWriter fw = null;

        try {
            fw = new FileWriter("input.lp");
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
      bw = new BufferedWriter(fw);
        try {
            fw.write("man(1.."+m_size+").\n");
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            fw.write("woman(1.."+w_size+").\n");
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    for(int i=0;i<m_size;i++)
        for(int k=0;k<split_m.get(i).length;k++)
             try {
                 fw.write("mrank("+(i+1)+","+(k+1)+","+split_m.get(i)[k]+").\n");
             } catch (IOException ex) {
                 Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
             }
        try {
            fw.write("\n");
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    for(int i=0;i<w_size;i++)
           for(int k=0;k<split_w.get(i).length;k++)
             try {
                 fw.write("wrank("+(i+1)+","+(k+1)+","+split_w.get(i)[k]+").\n");
             } catch (IOException ex) {
                 Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
             }
        try {
            fw.write("\n");
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }}

    else if(getSelectedButtonText(buttonGroup1) == "Preference"){
    List<String> lines = new ArrayList<String>();
    String s="";
     s = textArea.getText();
    lines = Arrays.asList(s.split("\n"));

  if(lines.size() < 2   ){
           JOptionPane.showMessageDialog(this, "Invalid Input!");
           return;
   }

       int m_size = Integer.parseInt(lines.get(0));
       int w_size = Integer.parseInt(lines.get(1));

   int m_maxLen = 0;
   int w_maxLen = 0;

   for(int i=2;i<m_size+2;i++ )
   {
       if(lines.get(i).length() > m_maxLen)
         m_maxLen = lines.get(i).length();
   }
    for(int i=m_size+2;i<w_size+m_size+2;i++ )
   {
       if(lines.get(i).length() > w_maxLen)
         w_maxLen = lines.get(i).length();
   }


        if(lines.size() != m_size + w_size + 2 || m_maxLen > 4*m_size || w_maxLen > 4*w_size ){
           JOptionPane.showMessageDialog(this, "Invalid Input!");
           return;
   }
       List<String[]> m_preflists;
       ArrayList<String[]> split_w = new ArrayList<String[]>();
       ArrayList<String[]> split_m = new ArrayList<String[]>();


      for(int i=0; i<m_size;i++)
      {
         String k=lines.get(i + 2);
         String[] l=k.split(" ");
          split_m.add(l);
      }

      for(int i=0; i<w_size;i++)
      {
         String k=lines.get(i + 2 + m_size);
         String[] l=k.split(" ");
          split_w.add(l);
      }


      BufferedWriter bw = null;
      FileWriter fw = null;

        try {
            fw = new FileWriter("input.lp");
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
      bw = new BufferedWriter(fw);
        try {
            fw.write("man(1.."+m_size+").\n");
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            fw.write("woman(1.."+w_size+").\n");
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }


 ArrayList<List<Tuple>> m_preflists1= new ArrayList<List<Tuple>>();
 int curr;
   for(int i=0;i<m_size;i++)
{
    String temp=lines.get(i+2);
    String rev=new StringBuilder(temp).toString();
    String [] split_gt = rev.split(" > ");
    curr = 1;
    List<Tuple> preflist=new ArrayList<Tuple>();
    for (int m=0;m<split_gt.length;m++)
    {
       String outer_split= split_gt[m];
       String[] split_eq=outer_split.split(" = ");
        for(int k=0;k<split_eq.length;k++)
        {
           String inner_split = split_eq[k];
           Tuple t;
           t = new Tuple(Integer.parseInt(inner_split),curr);
           preflist.add(t);
        }
        curr += 1;
         }
      m_preflists1.add(preflist);
    }


 ArrayList<List<Tuple>> w_preflists1= new ArrayList<List<Tuple>>();

   for(int i=0;i<m_size;i++)
{
    String temp=lines.get(i+2+m_size);
    String rev=new StringBuilder(temp).toString();
    String [] split_gt = rev.split(" > ");
    curr = 1;
    List<Tuple> preflist=new ArrayList<Tuple>();
    for (int m=0;m<split_gt.length;m++)
    {
       String outer_split= split_gt[m];
       String[] split_eq=outer_split.split(" = ");
        for(int k=0;k<split_eq.length;k++)
        {
           String inner_split = split_eq[k];
           Tuple t;
           t = new Tuple(Integer.parseInt(inner_split),curr);
           preflist.add(t);
        }
        curr += 1;
        }
      w_preflists1.add(preflist);
    }


    for(int i=0; i<m_size;i++)
        for(int k=0;k<m_preflists1.get(i).size();k++)
             try {
                 bw.write("mrank("+(i + 1)+","+m_preflists1.get(i).get(k).getx()+","+m_preflists1.get(i).get(k).gety()+").\n");
             } catch (IOException ex) {
                 Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
             }
        try {
            bw.write("\n");
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
      for(int i=0; i<w_size;i++)
        for(int k=0;k<w_preflists1.get(i).size();k++)
             try {
                 bw.write("wrank("+(i + 1)+","+w_preflists1.get(i).get(k).getx()+","+w_preflists1.get(i).get(k).gety()+").\n");
             } catch (IOException ex) {
                 Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
             }
        try {
            bw.write("\n");
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    else
    {JOptionPane.showMessageDialog(this, "Please specify the input format");
return;
    }
     if(jComboBox1.getSelectedItem()=="SMP with Ties and Inc.")
         command = "clingo --stats input.lp codes/smpti.lp 0";
    else if(jComboBox1.getSelectedItem()=="Sex Equal")
       command = "clingo --stats input.lp codes/smpti.lp codes/sexequal.lp 0";
     else if(jComboBox1.getSelectedItem()=="Min Regret")
       command = "clingo --stats input.lp codes/smpti.lp codes/minregret.lp 0";
     else if(jComboBox1.getSelectedItem()=="Egalitarian")
       command = "clingo --stats input.lp codes/smpti.lp codes/egalitarian.lp 0";
     else if(jComboBox1.getSelectedItem()=="Max Cardinality")
       command = "clingo --stats input.lp codes/smpti.lp codes/maxcardinality.lp 0";

  List<String> li= new ArrayList<String>(Arrays.asList(command.split(" ")));
  ProcessBuilder builder = new ProcessBuilder(li);
  builder.redirectErrorStream(true);
   String[] match=null;
    long start = System.nanoTime();
        try {
            Process p = builder.start();
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    Runtime rt = Runtime.getRuntime();
    Process pr=null;
        try {
            pr = rt.exec(command);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    BufferedReader stdInput = new BufferedReader(new InputStreamReader(pr.getInputStream()));
    long end = System.nanoTime();

     String line=null;
        try {
            line = stdInput.readLine();
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
     String output="";

     while (line != null)
     {
         output+=line+"\n";
        try {
            line=stdInput.readLine();
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
     }

    String[] lines = output.split("\n");

    for(int i=0;i<lines.length;i++)
    {
        if(lines[i].equals("OPTIMUM FOUND"))
        {
            match=lines[i-2].split(" ");
            String[] optval= lines[i-1].split(" ");
            double seconds = (double)(end-start) / 1000000000.0;
            System.out.println("running time: " +seconds+ " seconds\noptimization:"+optval[1]);
            break;
        }
          }
           String resultfile = "result.txt";
           FileWriter rw = null;
        try {
            rw = new FileWriter(resultfile);
            
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
           BufferedWriter bw = null;
	   bw = new BufferedWriter(rw);
      

      for(int i=0;i<lines.length;i++)
    {
        if(lines[i].equals("SATISFIABLE"))
        {
             match=lines[i-1].split(" ");
             double seconds = (double)(end-start) / 1000000000.0;
            //System.out.println("running time: " +seconds+ " seconds\n");
         break;
        }
}

        try {
            bw.write("  "+"M"+"    "+"W \n" );
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }


    for(int m=0;m<match.length;m++)
  {
    String word=match[m];
    if(word.substring(0,5).equals("marry"))
    {
        String[] arr=word.substring(6,9).split(",");
        try {
            bw.write("  "+ arr[0] + "    " + arr[1] + "\n");
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
  
}
       try {
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
   JOptionPane.showMessageDialog(this, "Result can be read from result.txt");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:



    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        int returnVal = fileChooser.showOpenDialog(this);
    if (returnVal == fileChooser.APPROVE_OPTION) {
        file = fileChooser.getSelectedFile();
        try {
          // What to do with the file, e.g. display it in a TextArea
          textArea.read( new FileReader( file.getAbsolutePath() ), null );
        } catch (IOException ex) {
          System.out.println("problem accessing file"+file.getAbsolutePath());
        }
    } else {
        System.out.println("File access cancelled by user.");
    }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
class MyCustomFilter extends javax.swing.filechooser.FileFilter {
        @Override
        public boolean accept(File file) {
            // Allow only directories, or files with ".txt" extension
            return file.isDirectory() || file.getAbsolutePath().endsWith(".txt");
        }
        @Override
        public String getDescription() {
            // This description will be displayed in the dialog,
            // hard-coded = ugly, should be done via I18N
            return "Text documents (*.txt)";
        }
    }
